# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fcacccef9156f5368e4fdf131dc45480381990bf42e4a4cb3373bf7ad5b460a201e6e8f2c397453bb4f9fc6ccd6a2501fcad35005f3acafb84212ea7cdcd2b0

test:
  secret_key_base: 7b9d807009df48bbdaa2300bcb14026727017a83ad8b022656b0e4ca71cb38d1671c1b0e4620584363f955c5bdc0ebeda53aae54d57180ba3e082c506857e931

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
